/**
 * Generate FACTS.md: every number this project is allowed to claim.
 *
 * Run: npm run facts
 *
 * WHY. A demo video is immutable once published, and its spoken and on-screen
 * numbers are claims exactly like a README's. The failure mode this file
 * prevents is real and already happened once during planning: a build document
 * asserted "Detonator assemblies UN0360, class 1.4B". The regulation says
 * 1.1B. Nothing in a review would have caught it, because a wrong figure that
 * looks plausible reads exactly like a right one.
 *
 * So every figure the README, the Devpost description, the video narration and
 * the UI copy are allowed to use is DERIVED HERE, from the committed corpus,
 * and `npm run verify:data` fails if a judge-facing document contains a number
 * this file did not produce.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { plainText } from "./ecfr.ts";
import { measureDivergence } from "../src/evidence/divergence.ts";
import { normalizeOrthography } from "../src/solver/corpus.ts";

const DATA = join(process.cwd(), "data");
const read = <T,>(f: string): T => JSON.parse(readFileSync(join(DATA, f), "utf8")) as T;

type Hmt = { entries: Array<{ name: string; class: string; un: string | null; pg: string | null; labels: string[]; forbidden: boolean; packingGroupVariant: boolean; symbols: { airOnly: boolean; vesselOnly: boolean } }> };
type Seg = { columns: string[]; rows: Array<{ key: string; division: string; label: string; note: string | null; cells: Record<string, string> }>; census: Record<string, number> };
type Comp = { groups: string[]; matrix: Record<string, Record<string, string>> };

const hmt = read<Hmt>("hmt.json");
const seg = read<Seg>("segregation_table.json");
const comp = read<Comp>("compatibility_table.json");
const stats = read<Record<string, unknown>>("stats.json");
const prov = readFileSync(join(DATA, "PROVENANCE.md"), "utf8");
const snapshot = /eCFR snapshot requested \| \`([\d-]+)\`/.exec(prov)?.[1] ?? "UNKNOWN";
const amended = /latest_amended_on\` \| \`([\d-]+)\`/.exec(prov)?.[1] ?? "UNKNOWN";

const byUn = (un: string) => hmt.entries.find((e) => e.un === un);
const cell = (rowDiv: string, col: string) => seg.rows.find((r) => r.division === rowDiv)?.cells[col] ?? "?";

/** The demo manifest, resolved from the corpus rather than remembered. */
const DEMO_UNS = ["UN1090", "UN1830", "UN1748", "UN1309", "UN0360"];
const demo = DEMO_UNS.map((un) => {
  const e = byUn(un);
  if (!e) throw new Error(`demo manifest: ${un} is not in the corpus`);
  return e;
});
const forbiddenDemo = hmt.entries.find((e) => e.forbidden && e.name === "Ammonium chlorate");
if (!forbiddenDemo) throw new Error("demo manifest: Ammonium chlorate not found among Forbidden entries");

// Verbatim clause text, pulled from the raw XML rather than retyped.
const raw173 = readFileSync(join(DATA, "raw", `173-21-forbidden@${snapshot}.xml`), "utf8");
const t173 = plainText(raw173);
const clause = (needle: string, len = 240) => {
  const i = t173.indexOf(needle);
  if (i < 0) throw new Error(`clause not found verbatim in 173.21: ${needle.slice(0, 50)}`);
  return t173.slice(i, i + len).trim();
};

const div = measureDivergence();

const nameBuckets = new Map<string, typeof hmt.entries>();
for (const e of hmt.entries) {
  const k = normalizeOrthography(e.name);
  const b = nameBuckets.get(k);
  if (b) b.push(e); else nameBuckets.set(k, [e]);
}
let unique = 0, pgOnly = 0, multiClass = 0, worstName = "", worstCount = 0;
for (const [k, v] of nameBuckets) {
  const classes = new Set(v.map((e) => e.class));
  if (v.length === 1) { unique++; continue; }
  if (classes.size > 1) {
    multiClass++;
    if (classes.size > worstCount) { worstCount = classes.size; worstName = k; }
  } else pgOnly++;
}
const forbiddenAmbiguous = hmt.entries.filter(
  (e) => e.forbidden && new Set((nameBuckets.get(normalizeOrthography(e.name)) ?? []).map((x) => x.class)).size > 1,
).length;
const nameStats = { unique, pgOnly, multiClass, worstName, worstCount, forbiddenAmbiguous };

const spelling = {
  sulph: hmt.entries.filter((e) => /sulph/i.test(e.name)).length,
  sulf: hmt.entries.filter((e) => /sulf/i.test(e.name)).length,
  caesium: hmt.entries.filter((e) => /caesium/i.test(e.name)).length,
  cesium: hmt.entries.filter((e) => /\bcesium/i.test(e.name)).length,
};

const out = `<!-- GENERATED BY \`npm run facts\`. DO NOT EDIT BY HAND. -->
# Fact sheet

Every number this project is permitted to claim, derived from the committed
corpus. The README, the Devpost description, the demo-video narration and all
UI copy draw from this file and from nothing else. \`npm run verify:data\`
fails if a judge-facing document states a corpus figure that does not appear
here.

Corpus pin: eCFR snapshot \`${snapshot}\`, title 49 \`latest_amended_on ${amended}\`.

## Corpus shape

| Claim | Value |
|---|---:|
| Physical rows in the 49 CFR 172.101 table | ${stats.physicalRows} |
| Entries after resolving packing-group continuations | ${stats.entries} |
| Entries designated \`Forbidden\` in column 3 | ${stats.forbidden} |
| Of those, how many carry a UN number | ${hmt.entries.filter((e) => e.forbidden && e.un).length} |
| Packing-group continuation rows recovered | ${stats.packingGroupVariants} |
| Entries carrying a UN, NA or ID number | ${stats.withUnNumber} |
| Rows a UN-keyed index keeps | ${stats.withUnNumber} |
| Rows a UN-keyed index silently drops | ${(stats.physicalRows as number) - (stats.withUnNumber as number)} |
| Synonym pointer rows (\`X, see Y\`) | ${stats.synonymPointers} |
| Entries with more than one label code (subsidiary hazard fires) | ${stats.multiLabel} |
| Share of entries with a subsidiary hazard | ${(((stats.multiLabel as number) / (stats.entries as number)) * 100).toFixed(1)}% |
| Entries regulated only by aircraft or vessel, so outside Part 177 | ${stats.modeExcludedFromPart177} |

## The segregation matrix, 49 CFR 177.848(d)

| Claim | Value |
|---|---:|
| Rows | ${seg.rows.length} |
| Columns | ${seg.columns.length} |
| Cells | ${seg.rows.length * seg.columns.length} |
| \`X\` may not be loaded together | ${seg.census.X} |
| \`O\` may not be together unless separated | ${seg.census.O} |
| \`*\` governed by the compatibility table | ${seg.census["*"]} |
| blank, no restriction | ${seg.census.blank} |
| Rows carrying note A | ${seg.rows.filter((r) => r.note === "A").length} |
| Division 2.3 rows (Zone A and Zone B are separate) | ${seg.rows.filter((r) => r.division === "2.3").length} |

## The compatibility table, 49 CFR 177.848(f)

| Claim | Value |
|---|---:|
| Compatibility groups | ${comp.groups.length} |
| Cells | ${comp.groups.length ** 2} |
| Distinct cell codes | ${[...new Set(Object.values(comp.matrix).flatMap((r) => Object.values(r)))].filter(Boolean).map((c) => `\`${c}\``).join(", ")} |

## The demo manifest, resolved from the corpus

| Item | UN | Class | PG | Labels |
|---|---|---|---|---|
${demo.map((e) => `| ${e.name} | \`${e.un}\` | \`${e.class}\` | ${e.pg ?? "n/a"} | ${e.labels.map((l) => `\`${l}\``).join(", ") || "none"} |`).join("\n")}
| ${forbiddenDemo.name} | **none** | \`${forbiddenDemo.class}\` | n/a | none |

## The two demonstrations, with their cells

**1. The \`O\` cell that a barrier does not rescue.**
Sulfuric acid (\`${byUn("UN1830")!.class}\`) against calcium hypochlorite
(\`${byUn("UN1748")!.class}\`). The 177.848(d) cell for row "Corrosive liquids"
against column "5.1" is **\`${cell("8", "5.1")}\`**, which on its face means the two may
travel together once separated. 177.848(e)(3) then removes that option outright:
Class 8 liquids may not be loaded above or adjacent to Class 5 materials
regardless of separation. An agent reasoning from the matrix alone clears this
load.

**2. The material with no UN number.**
${forbiddenDemo.name} is \`${forbiddenDemo.class}\` and has no identification number.
49 CFR 173.21(a) forbids offering for transportation:

> ${clause("Materials that are designated", 120)}

and 172.101(d)(1):

> A material for which the entry in this column is "Forbidden" may not be offered for transportation or transported.

Any index keyed on a UN number returns nothing for all ${stats.forbidden} of these.

## The measured divergence, 49 CFR 177.848(d) against the whole regulation

Recomputed here and served live at \`/api/measure\`. This is the ONLY source for
these figures: the demo-video narration, the README and the submission all draw
from this table so they cannot diverge from one another.

| Claim | Value |
|---|---:|
| Hazard categories the table indexes | ${div.categories} |
| Configurations examined (ordered pairs x barrier x truckload carve-out) | ${div.configurationsExamined} |
| Configurations the 177.848(d) table alone clears | ${div.tableAloneClears} |
| Of those, configurations the full regulation forbids | ${div.divergent} |
| Share of table-cleared configurations that are actually prohibited | ${(div.divergentShareOfCleared * 100).toFixed(1)}% |
${Object.entries(div.byGround).map(([k, v]) => `| Divergent on ground \`${k}\` | ${v} |`).join("\n")}

This measures the SIZE OF THE GAP an agent reasons across when it treats the
table as the whole rule. It is not a measurement of any model's accuracy, and no
language model was run to produce it.

## Name resolution, and where a proper shipping name is NOT an identifier

Derived here from the committed corpus. A proper shipping name looks like a key
and is not one.

| Claim | Value |
|---|---:|
| Names resolving to exactly one 172.101 entry | ${nameStats.unique} |
| Names whose entries differ only by packing group, so the class is shared | ${nameStats.pgOnly} |
| **Names spanning MORE THAN ONE hazard class, which the solver refuses** | **${nameStats.multiClass}** |
| Widest such name, by distinct classes | \`${nameStats.worstName}\` at ${nameStats.worstCount} |
| Forbidden materials that are name-ambiguous | ${nameStats.forbiddenAmbiguous} |

The last row matters because none of the 256 Forbidden entries has an
identification number, so a name is the ONLY way to reach them. It is
${nameStats.forbiddenAmbiguous}, so refusing ambiguous names costs nothing there.

## British and American spelling in the federal table

The 172.101 table is not internally consistent, so an index that matches names
literally loses real materials in both directions.

| Claim | Value |
|---|---:|
| Entries spelled with British \`-sulph-\` | ${spelling.sulph} |
| Entries spelled with American \`-sulf-\` | ${spelling.sulf} |
| Entries spelled \`Caesium\` | ${spelling.caesium} |
| Entries spelled \`Cesium\` | ${spelling.cesium} |

## Figures that are NOT derived here and must be sourced in place

These are real and citable but come from outside the corpus, so every use must
carry its source inline. They are listed so a reviewer can find them.

| Figure | Source to cite |
|---|---|
| PHMSA maximum civil penalty per violation per day | 49 U.S.C. 5123(a), as adjusted at 89 FR 106282 |
| Separation satisfied by barriers, not air space | PHMSA interpretations 08-0143 and 03-0300 |
| "Truckload" means loaded by a single shipper | PHMSA interpretation 04-0031 |
| PHMSA maximum civil penalty, current dollar figure | look it up at 49 CFR 107.329 before stating it |

NOT AVAILABLE and must never be asserted: any unaided-model clearance rate. No
OpenAI key exists for this project, so no model arm was ever run. Use the
measured divergence above, which needs no model.

Nothing else may be stated as a number.
`;

writeFileSync(join(process.cwd(), "FACTS.md"), out);
process.stdout.write(`FACTS.md written\n  ${stats.forbidden} Forbidden, ${stats.entries} entries, ${seg.rows.length}x${seg.columns.length} matrix\n  demo manifest resolved: ${demo.map((e) => `${e.un}=${e.class}`).join(" ")}\n`);
